// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/runtimeconfig/v1beta1/runtimeconfig.proto
// Original file comments:
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Cloud.Runtimeconfig.V1Beta1 {
  /// <summary>
  ///  RuntimeConfig API represents configuration objects and operations on those
  ///  configuration objects.
  ///  RuntimeConfig objects consist of Variables logically grouped in the those
  ///  objects.
  ///  Variables are simple key-value pairs. Variables can be watched for changes or
  ///  deletions. Variable key can be hieararchical, e.g. ports/serving_port,
  ///  ports/monitoring_port, etc. Variable names can be hierarchical. No variable
  ///  name can be prefix of another.
  ///  Config objects represent logical containers for variables, e.g. flags,
  ///  passwords, etc.
  /// </summary>
  public static class RuntimeConfigManager
  {
    static readonly string __ServiceName = "google.cloud.runtimeconfig.v1beta1.RuntimeConfigManager";

    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest> __Marshaller_ListConfigsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse> __Marshaller_ListConfigsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest> __Marshaller_GetConfigRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> __Marshaller_RuntimeConfig = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest> __Marshaller_CreateConfigRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest> __Marshaller_UpdateConfigRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest> __Marshaller_DeleteConfigRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest> __Marshaller_ListVariablesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse> __Marshaller_ListVariablesResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest> __Marshaller_GetVariableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> __Marshaller_Variable = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.Variable.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest> __Marshaller_WatchVariableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest> __Marshaller_CreateVariableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest> __Marshaller_UpdateVariableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest> __Marshaller_DeleteVariableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest> __Marshaller_ListWaitersRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse> __Marshaller_ListWaitersResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest> __Marshaller_GetWaiterRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter> __Marshaller_Waiter = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest> __Marshaller_CreateWaiterRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.LongRunning.Operation> __Marshaller_Operation = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.LongRunning.Operation.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest> __Marshaller_DeleteWaiterRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest.Parser.ParseFrom);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse> __Method_ListConfigs = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListConfigs",
        __Marshaller_ListConfigsRequest,
        __Marshaller_ListConfigsResponse);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> __Method_GetConfig = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig>(
        MethodType.Unary,
        __ServiceName,
        "GetConfig",
        __Marshaller_GetConfigRequest,
        __Marshaller_RuntimeConfig);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> __Method_CreateConfig = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig>(
        MethodType.Unary,
        __ServiceName,
        "CreateConfig",
        __Marshaller_CreateConfigRequest,
        __Marshaller_RuntimeConfig);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> __Method_UpdateConfig = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig>(
        MethodType.Unary,
        __ServiceName,
        "UpdateConfig",
        __Marshaller_UpdateConfigRequest,
        __Marshaller_RuntimeConfig);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteConfig = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteConfig",
        __Marshaller_DeleteConfigRequest,
        __Marshaller_Empty);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse> __Method_ListVariables = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListVariables",
        __Marshaller_ListVariablesRequest,
        __Marshaller_ListVariablesResponse);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> __Method_GetVariable = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable>(
        MethodType.Unary,
        __ServiceName,
        "GetVariable",
        __Marshaller_GetVariableRequest,
        __Marshaller_Variable);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> __Method_WatchVariable = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable>(
        MethodType.Unary,
        __ServiceName,
        "WatchVariable",
        __Marshaller_WatchVariableRequest,
        __Marshaller_Variable);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> __Method_CreateVariable = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable>(
        MethodType.Unary,
        __ServiceName,
        "CreateVariable",
        __Marshaller_CreateVariableRequest,
        __Marshaller_Variable);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> __Method_UpdateVariable = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Variable>(
        MethodType.Unary,
        __ServiceName,
        "UpdateVariable",
        __Marshaller_UpdateVariableRequest,
        __Marshaller_Variable);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteVariable = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteVariable",
        __Marshaller_DeleteVariableRequest,
        __Marshaller_Empty);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse> __Method_ListWaiters = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListWaiters",
        __Marshaller_ListWaitersRequest,
        __Marshaller_ListWaitersResponse);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter> __Method_GetWaiter = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest, global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter>(
        MethodType.Unary,
        __ServiceName,
        "GetWaiter",
        __Marshaller_GetWaiterRequest,
        __Marshaller_Waiter);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest, global::Google.LongRunning.Operation> __Method_CreateWaiter = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest, global::Google.LongRunning.Operation>(
        MethodType.Unary,
        __ServiceName,
        "CreateWaiter",
        __Marshaller_CreateWaiterRequest,
        __Marshaller_Operation);

    static readonly Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteWaiter = new Method<global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteWaiter",
        __Marshaller_DeleteWaiterRequest,
        __Marshaller_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeconfigReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RuntimeConfigManager</summary>
    public abstract class RuntimeConfigManagerBase
    {
      /// <summary>
      ///  Lists all the RuntimeConfig resources within project.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse> ListConfigs(global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets information about a RuntimeConfig resource.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> GetConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Creates a new RuntimeConfig resource. The configuration name must be
      ///  unique within project.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> CreateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Updates a RuntimeConfig resource. The configuration must exist beforehand.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> UpdateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Deletes a RuntimeConfig resource.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Lists variables within given a configuration, matching any provided filters.
      ///  This only lists variable names, not the values.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse> ListVariables(global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets information about a single variable.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> GetVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Watches a specific variable and waits for a change in the variable's value.
      ///  When there is a change, this method returns the new value or times out.
      ///
      ///  If a variable is deleted while being watched, the `variableState` state is
      ///  set to `DELETED` and the method returns the last known variable `value`.
      ///
      ///  If you set the deadline for watching to a larger value than internal timeout
      ///  (60 seconds), the current variable value is returned and the `variableState`
      ///  will be `VARIABLE_STATE_UNSPECIFIED`.
      ///
      ///  To learn more about creating a watcher, read the
      ///  [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
      ///  documentation.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> WatchVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Creates a variable within the given configuration. You cannot create
      ///  a variable with a name that is a prefix of an existing variable name, or a
      ///  name that has an existing variable name as a prefix.
      ///
      ///  To learn more about creating a variable, read the
      ///  [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
      ///  documentation.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> CreateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Updates an existing variable with a new value.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> UpdateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Deletes a variable or multiple variables.
      ///
      ///  If you specify a variable name, then that variable is deleted. If you
      ///  specify a prefix and `recursive` is true, then all variables with that
      ///  prefix are deleted. You must set a `recursive` to true if you delete
      ///  variables by prefix.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  List waiters within the given configuration.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse> ListWaiters(global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets information about a single waiter.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter> GetWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Creates a Waiter resource. This operation returns a long-running Operation
      ///  resource which can be polled for completion. However, a waiter with the
      ///  given name will exist (and can be retrieved) prior to the operation
      ///  completing. If the operation fails, the failed Waiter resource will
      ///  still exist and must be deleted prior to subsequent creation attempts.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.LongRunning.Operation> CreateWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Deletes the waiter with the specified name.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RuntimeConfigManager</summary>
    public class RuntimeConfigManagerClient : ClientBase<RuntimeConfigManagerClient>
    {
      /// <summary>Creates a new client for RuntimeConfigManager</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RuntimeConfigManagerClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RuntimeConfigManager that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RuntimeConfigManagerClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RuntimeConfigManagerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RuntimeConfigManagerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Lists all the RuntimeConfig resources within project.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse ListConfigs(global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListConfigs(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists all the RuntimeConfig resources within project.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse ListConfigs(global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListConfigs, null, options, request);
      }
      /// <summary>
      ///  Lists all the RuntimeConfig resources within project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse> ListConfigsAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListConfigsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists all the RuntimeConfig resources within project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsResponse> ListConfigsAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListConfigsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListConfigs, null, options, request);
      }
      /// <summary>
      ///  Gets information about a RuntimeConfig resource.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig GetConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetConfig(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a RuntimeConfig resource.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig GetConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetConfig, null, options, request);
      }
      /// <summary>
      ///  Gets information about a RuntimeConfig resource.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> GetConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetConfigAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a RuntimeConfig resource.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> GetConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetConfigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetConfig, null, options, request);
      }
      /// <summary>
      ///  Creates a new RuntimeConfig resource. The configuration name must be
      ///  unique within project.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig CreateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateConfig(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a new RuntimeConfig resource. The configuration name must be
      ///  unique within project.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig CreateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateConfig, null, options, request);
      }
      /// <summary>
      ///  Creates a new RuntimeConfig resource. The configuration name must be
      ///  unique within project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> CreateConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateConfigAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a new RuntimeConfig resource. The configuration name must be
      ///  unique within project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> CreateConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateConfigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateConfig, null, options, request);
      }
      /// <summary>
      ///  Updates a RuntimeConfig resource. The configuration must exist beforehand.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig UpdateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateConfig(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates a RuntimeConfig resource. The configuration must exist beforehand.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig UpdateConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateConfig, null, options, request);
      }
      /// <summary>
      ///  Updates a RuntimeConfig resource. The configuration must exist beforehand.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> UpdateConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateConfigAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates a RuntimeConfig resource. The configuration must exist beforehand.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.RuntimeConfig> UpdateConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateConfigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateConfig, null, options, request);
      }
      /// <summary>
      ///  Deletes a RuntimeConfig resource.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteConfig(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a RuntimeConfig resource.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteConfig(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteConfig, null, options, request);
      }
      /// <summary>
      ///  Deletes a RuntimeConfig resource.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteConfigAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a RuntimeConfig resource.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteConfigAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteConfigRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteConfig, null, options, request);
      }
      /// <summary>
      ///  Lists variables within given a configuration, matching any provided filters.
      ///  This only lists variable names, not the values.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse ListVariables(global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListVariables(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists variables within given a configuration, matching any provided filters.
      ///  This only lists variable names, not the values.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse ListVariables(global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListVariables, null, options, request);
      }
      /// <summary>
      ///  Lists variables within given a configuration, matching any provided filters.
      ///  This only lists variable names, not the values.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse> ListVariablesAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListVariablesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists variables within given a configuration, matching any provided filters.
      ///  This only lists variable names, not the values.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesResponse> ListVariablesAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListVariablesRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListVariables, null, options, request);
      }
      /// <summary>
      ///  Gets information about a single variable.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable GetVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVariable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a single variable.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable GetVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVariable, null, options, request);
      }
      /// <summary>
      ///  Gets information about a single variable.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> GetVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVariableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a single variable.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> GetVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetVariableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVariable, null, options, request);
      }
      /// <summary>
      ///  Watches a specific variable and waits for a change in the variable's value.
      ///  When there is a change, this method returns the new value or times out.
      ///
      ///  If a variable is deleted while being watched, the `variableState` state is
      ///  set to `DELETED` and the method returns the last known variable `value`.
      ///
      ///  If you set the deadline for watching to a larger value than internal timeout
      ///  (60 seconds), the current variable value is returned and the `variableState`
      ///  will be `VARIABLE_STATE_UNSPECIFIED`.
      ///
      ///  To learn more about creating a watcher, read the
      ///  [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
      ///  documentation.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable WatchVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return WatchVariable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Watches a specific variable and waits for a change in the variable's value.
      ///  When there is a change, this method returns the new value or times out.
      ///
      ///  If a variable is deleted while being watched, the `variableState` state is
      ///  set to `DELETED` and the method returns the last known variable `value`.
      ///
      ///  If you set the deadline for watching to a larger value than internal timeout
      ///  (60 seconds), the current variable value is returned and the `variableState`
      ///  will be `VARIABLE_STATE_UNSPECIFIED`.
      ///
      ///  To learn more about creating a watcher, read the
      ///  [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
      ///  documentation.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable WatchVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_WatchVariable, null, options, request);
      }
      /// <summary>
      ///  Watches a specific variable and waits for a change in the variable's value.
      ///  When there is a change, this method returns the new value or times out.
      ///
      ///  If a variable is deleted while being watched, the `variableState` state is
      ///  set to `DELETED` and the method returns the last known variable `value`.
      ///
      ///  If you set the deadline for watching to a larger value than internal timeout
      ///  (60 seconds), the current variable value is returned and the `variableState`
      ///  will be `VARIABLE_STATE_UNSPECIFIED`.
      ///
      ///  To learn more about creating a watcher, read the
      ///  [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
      ///  documentation.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> WatchVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return WatchVariableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Watches a specific variable and waits for a change in the variable's value.
      ///  When there is a change, this method returns the new value or times out.
      ///
      ///  If a variable is deleted while being watched, the `variableState` state is
      ///  set to `DELETED` and the method returns the last known variable `value`.
      ///
      ///  If you set the deadline for watching to a larger value than internal timeout
      ///  (60 seconds), the current variable value is returned and the `variableState`
      ///  will be `VARIABLE_STATE_UNSPECIFIED`.
      ///
      ///  To learn more about creating a watcher, read the
      ///  [Watching a Variable for Changes](/deployment-manager/runtime-configurator/watching-a-variable)
      ///  documentation.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> WatchVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.WatchVariableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_WatchVariable, null, options, request);
      }
      /// <summary>
      ///  Creates a variable within the given configuration. You cannot create
      ///  a variable with a name that is a prefix of an existing variable name, or a
      ///  name that has an existing variable name as a prefix.
      ///
      ///  To learn more about creating a variable, read the
      ///  [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
      ///  documentation.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable CreateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateVariable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a variable within the given configuration. You cannot create
      ///  a variable with a name that is a prefix of an existing variable name, or a
      ///  name that has an existing variable name as a prefix.
      ///
      ///  To learn more about creating a variable, read the
      ///  [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
      ///  documentation.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable CreateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateVariable, null, options, request);
      }
      /// <summary>
      ///  Creates a variable within the given configuration. You cannot create
      ///  a variable with a name that is a prefix of an existing variable name, or a
      ///  name that has an existing variable name as a prefix.
      ///
      ///  To learn more about creating a variable, read the
      ///  [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
      ///  documentation.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> CreateVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateVariableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a variable within the given configuration. You cannot create
      ///  a variable with a name that is a prefix of an existing variable name, or a
      ///  name that has an existing variable name as a prefix.
      ///
      ///  To learn more about creating a variable, read the
      ///  [Setting and Getting Data](/deployment-manager/runtime-configurator/set-and-get-variables)
      ///  documentation.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> CreateVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateVariableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateVariable, null, options, request);
      }
      /// <summary>
      ///  Updates an existing variable with a new value.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable UpdateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateVariable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates an existing variable with a new value.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Variable UpdateVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateVariable, null, options, request);
      }
      /// <summary>
      ///  Updates an existing variable with a new value.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> UpdateVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateVariableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates an existing variable with a new value.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Variable> UpdateVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.UpdateVariableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateVariable, null, options, request);
      }
      /// <summary>
      ///  Deletes a variable or multiple variables.
      ///
      ///  If you specify a variable name, then that variable is deleted. If you
      ///  specify a prefix and `recursive` is true, then all variables with that
      ///  prefix are deleted. You must set a `recursive` to true if you delete
      ///  variables by prefix.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteVariable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a variable or multiple variables.
      ///
      ///  If you specify a variable name, then that variable is deleted. If you
      ///  specify a prefix and `recursive` is true, then all variables with that
      ///  prefix are deleted. You must set a `recursive` to true if you delete
      ///  variables by prefix.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVariable(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteVariable, null, options, request);
      }
      /// <summary>
      ///  Deletes a variable or multiple variables.
      ///
      ///  If you specify a variable name, then that variable is deleted. If you
      ///  specify a prefix and `recursive` is true, then all variables with that
      ///  prefix are deleted. You must set a `recursive` to true if you delete
      ///  variables by prefix.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteVariableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a variable or multiple variables.
      ///
      ///  If you specify a variable name, then that variable is deleted. If you
      ///  specify a prefix and `recursive` is true, then all variables with that
      ///  prefix are deleted. You must set a `recursive` to true if you delete
      ///  variables by prefix.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVariableAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteVariableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteVariable, null, options, request);
      }
      /// <summary>
      ///  List waiters within the given configuration.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse ListWaiters(global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListWaiters(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  List waiters within the given configuration.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse ListWaiters(global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListWaiters, null, options, request);
      }
      /// <summary>
      ///  List waiters within the given configuration.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse> ListWaitersAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListWaitersAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  List waiters within the given configuration.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersResponse> ListWaitersAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.ListWaitersRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListWaiters, null, options, request);
      }
      /// <summary>
      ///  Gets information about a single waiter.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter GetWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetWaiter(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a single waiter.
      /// </summary>
      public virtual global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter GetWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWaiter, null, options, request);
      }
      /// <summary>
      ///  Gets information about a single waiter.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter> GetWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetWaiterAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets information about a single waiter.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Runtimeconfig.V1Beta1.Waiter> GetWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.GetWaiterRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWaiter, null, options, request);
      }
      /// <summary>
      ///  Creates a Waiter resource. This operation returns a long-running Operation
      ///  resource which can be polled for completion. However, a waiter with the
      ///  given name will exist (and can be retrieved) prior to the operation
      ///  completing. If the operation fails, the failed Waiter resource will
      ///  still exist and must be deleted prior to subsequent creation attempts.
      /// </summary>
      public virtual global::Google.LongRunning.Operation CreateWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateWaiter(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a Waiter resource. This operation returns a long-running Operation
      ///  resource which can be polled for completion. However, a waiter with the
      ///  given name will exist (and can be retrieved) prior to the operation
      ///  completing. If the operation fails, the failed Waiter resource will
      ///  still exist and must be deleted prior to subsequent creation attempts.
      /// </summary>
      public virtual global::Google.LongRunning.Operation CreateWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWaiter, null, options, request);
      }
      /// <summary>
      ///  Creates a Waiter resource. This operation returns a long-running Operation
      ///  resource which can be polled for completion. However, a waiter with the
      ///  given name will exist (and can be retrieved) prior to the operation
      ///  completing. If the operation fails, the failed Waiter resource will
      ///  still exist and must be deleted prior to subsequent creation attempts.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> CreateWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateWaiterAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a Waiter resource. This operation returns a long-running Operation
      ///  resource which can be polled for completion. However, a waiter with the
      ///  given name will exist (and can be retrieved) prior to the operation
      ///  completing. If the operation fails, the failed Waiter resource will
      ///  still exist and must be deleted prior to subsequent creation attempts.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> CreateWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.CreateWaiterRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWaiter, null, options, request);
      }
      /// <summary>
      ///  Deletes the waiter with the specified name.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteWaiter(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes the waiter with the specified name.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteWaiter(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteWaiter, null, options, request);
      }
      /// <summary>
      ///  Deletes the waiter with the specified name.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteWaiterAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes the waiter with the specified name.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteWaiterAsync(global::Google.Cloud.Runtimeconfig.V1Beta1.DeleteWaiterRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteWaiter, null, options, request);
      }
      protected override RuntimeConfigManagerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RuntimeConfigManagerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(RuntimeConfigManagerBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListConfigs, serviceImpl.ListConfigs)
          .AddMethod(__Method_GetConfig, serviceImpl.GetConfig)
          .AddMethod(__Method_CreateConfig, serviceImpl.CreateConfig)
          .AddMethod(__Method_UpdateConfig, serviceImpl.UpdateConfig)
          .AddMethod(__Method_DeleteConfig, serviceImpl.DeleteConfig)
          .AddMethod(__Method_ListVariables, serviceImpl.ListVariables)
          .AddMethod(__Method_GetVariable, serviceImpl.GetVariable)
          .AddMethod(__Method_WatchVariable, serviceImpl.WatchVariable)
          .AddMethod(__Method_CreateVariable, serviceImpl.CreateVariable)
          .AddMethod(__Method_UpdateVariable, serviceImpl.UpdateVariable)
          .AddMethod(__Method_DeleteVariable, serviceImpl.DeleteVariable)
          .AddMethod(__Method_ListWaiters, serviceImpl.ListWaiters)
          .AddMethod(__Method_GetWaiter, serviceImpl.GetWaiter)
          .AddMethod(__Method_CreateWaiter, serviceImpl.CreateWaiter)
          .AddMethod(__Method_DeleteWaiter, serviceImpl.DeleteWaiter).Build();
    }

  }
}
#endregion
