// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/bigtable_table_admin.proto
// Original file comments:
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Bigtable.Admin.V2 {
  /// <summary>
  ///  Service for creating, configuring, and deleting Cloud Bigtable tables.
  ///  Provides access to the table schemas only, not the data stored within
  ///  the tables.
  /// </summary>
  public static class BigtableTableAdmin
  {
    static readonly string __ServiceName = "google.bigtable.admin.v2.BigtableTableAdmin";

    static readonly Marshaller<global::Google.Bigtable.Admin.V2.CreateTableRequest> __Marshaller_CreateTableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.CreateTableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.Table> __Marshaller_Table = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.Table.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.ListTablesRequest> __Marshaller_ListTablesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.ListTablesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.ListTablesResponse> __Marshaller_ListTablesResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.ListTablesResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.GetTableRequest> __Marshaller_GetTableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.GetTableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.DeleteTableRequest> __Marshaller_DeleteTableRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.DeleteTableRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest> __Marshaller_ModifyColumnFamiliesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Bigtable.Admin.V2.DropRowRangeRequest> __Marshaller_DropRowRangeRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Bigtable.Admin.V2.DropRowRangeRequest.Parser.ParseFrom);

    static readonly Method<global::Google.Bigtable.Admin.V2.CreateTableRequest, global::Google.Bigtable.Admin.V2.Table> __Method_CreateTable = new Method<global::Google.Bigtable.Admin.V2.CreateTableRequest, global::Google.Bigtable.Admin.V2.Table>(
        MethodType.Unary,
        __ServiceName,
        "CreateTable",
        __Marshaller_CreateTableRequest,
        __Marshaller_Table);

    static readonly Method<global::Google.Bigtable.Admin.V2.ListTablesRequest, global::Google.Bigtable.Admin.V2.ListTablesResponse> __Method_ListTables = new Method<global::Google.Bigtable.Admin.V2.ListTablesRequest, global::Google.Bigtable.Admin.V2.ListTablesResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListTables",
        __Marshaller_ListTablesRequest,
        __Marshaller_ListTablesResponse);

    static readonly Method<global::Google.Bigtable.Admin.V2.GetTableRequest, global::Google.Bigtable.Admin.V2.Table> __Method_GetTable = new Method<global::Google.Bigtable.Admin.V2.GetTableRequest, global::Google.Bigtable.Admin.V2.Table>(
        MethodType.Unary,
        __ServiceName,
        "GetTable",
        __Marshaller_GetTableRequest,
        __Marshaller_Table);

    static readonly Method<global::Google.Bigtable.Admin.V2.DeleteTableRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteTable = new Method<global::Google.Bigtable.Admin.V2.DeleteTableRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteTable",
        __Marshaller_DeleteTableRequest,
        __Marshaller_Empty);

    static readonly Method<global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest, global::Google.Bigtable.Admin.V2.Table> __Method_ModifyColumnFamilies = new Method<global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest, global::Google.Bigtable.Admin.V2.Table>(
        MethodType.Unary,
        __ServiceName,
        "ModifyColumnFamilies",
        __Marshaller_ModifyColumnFamiliesRequest,
        __Marshaller_Table);

    static readonly Method<global::Google.Bigtable.Admin.V2.DropRowRangeRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DropRowRange = new Method<global::Google.Bigtable.Admin.V2.DropRowRangeRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DropRowRange",
        __Marshaller_DropRowRangeRequest,
        __Marshaller_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Bigtable.Admin.V2.BigtableTableAdminReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BigtableTableAdmin</summary>
    public abstract class BigtableTableAdminBase
    {
      /// <summary>
      ///  Creates a new table in the specified instance.
      ///  The table can be created with a full set of initial column families,
      ///  specified in the request.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Bigtable.Admin.V2.Table> CreateTable(global::Google.Bigtable.Admin.V2.CreateTableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Lists all tables served from a specified instance.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Bigtable.Admin.V2.ListTablesResponse> ListTables(global::Google.Bigtable.Admin.V2.ListTablesRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets metadata information about the specified table.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Bigtable.Admin.V2.Table> GetTable(global::Google.Bigtable.Admin.V2.GetTableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Permanently deletes a specified table and all of its data.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTable(global::Google.Bigtable.Admin.V2.DeleteTableRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Atomically performs a series of column family modifications
      ///  on the specified table.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Bigtable.Admin.V2.Table> ModifyColumnFamilies(global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Permanently drop/delete a row range from a specified table. The request can
      ///  specify whether to delete all rows in a table, or only those that match a
      ///  particular prefix.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DropRowRange(global::Google.Bigtable.Admin.V2.DropRowRangeRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BigtableTableAdmin</summary>
    public class BigtableTableAdminClient : ClientBase<BigtableTableAdminClient>
    {
      /// <summary>Creates a new client for BigtableTableAdmin</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BigtableTableAdminClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BigtableTableAdmin that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BigtableTableAdminClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BigtableTableAdminClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BigtableTableAdminClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Creates a new table in the specified instance.
      ///  The table can be created with a full set of initial column families,
      ///  specified in the request.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table CreateTable(global::Google.Bigtable.Admin.V2.CreateTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateTable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a new table in the specified instance.
      ///  The table can be created with a full set of initial column families,
      ///  specified in the request.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table CreateTable(global::Google.Bigtable.Admin.V2.CreateTableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTable, null, options, request);
      }
      /// <summary>
      ///  Creates a new table in the specified instance.
      ///  The table can be created with a full set of initial column families,
      ///  specified in the request.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> CreateTableAsync(global::Google.Bigtable.Admin.V2.CreateTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateTableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates a new table in the specified instance.
      ///  The table can be created with a full set of initial column families,
      ///  specified in the request.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> CreateTableAsync(global::Google.Bigtable.Admin.V2.CreateTableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTable, null, options, request);
      }
      /// <summary>
      ///  Lists all tables served from a specified instance.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.ListTablesResponse ListTables(global::Google.Bigtable.Admin.V2.ListTablesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListTables(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists all tables served from a specified instance.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.ListTablesResponse ListTables(global::Google.Bigtable.Admin.V2.ListTablesRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListTables, null, options, request);
      }
      /// <summary>
      ///  Lists all tables served from a specified instance.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.ListTablesResponse> ListTablesAsync(global::Google.Bigtable.Admin.V2.ListTablesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListTablesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists all tables served from a specified instance.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.ListTablesResponse> ListTablesAsync(global::Google.Bigtable.Admin.V2.ListTablesRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListTables, null, options, request);
      }
      /// <summary>
      ///  Gets metadata information about the specified table.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table GetTable(global::Google.Bigtable.Admin.V2.GetTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetTable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets metadata information about the specified table.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table GetTable(global::Google.Bigtable.Admin.V2.GetTableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTable, null, options, request);
      }
      /// <summary>
      ///  Gets metadata information about the specified table.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> GetTableAsync(global::Google.Bigtable.Admin.V2.GetTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetTableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets metadata information about the specified table.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> GetTableAsync(global::Google.Bigtable.Admin.V2.GetTableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTable, null, options, request);
      }
      /// <summary>
      ///  Permanently deletes a specified table and all of its data.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTable(global::Google.Bigtable.Admin.V2.DeleteTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteTable(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Permanently deletes a specified table and all of its data.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTable(global::Google.Bigtable.Admin.V2.DeleteTableRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteTable, null, options, request);
      }
      /// <summary>
      ///  Permanently deletes a specified table and all of its data.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTableAsync(global::Google.Bigtable.Admin.V2.DeleteTableRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteTableAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Permanently deletes a specified table and all of its data.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTableAsync(global::Google.Bigtable.Admin.V2.DeleteTableRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteTable, null, options, request);
      }
      /// <summary>
      ///  Atomically performs a series of column family modifications
      ///  on the specified table.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table ModifyColumnFamilies(global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModifyColumnFamilies(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Atomically performs a series of column family modifications
      ///  on the specified table.
      /// </summary>
      public virtual global::Google.Bigtable.Admin.V2.Table ModifyColumnFamilies(global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ModifyColumnFamilies, null, options, request);
      }
      /// <summary>
      ///  Atomically performs a series of column family modifications
      ///  on the specified table.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> ModifyColumnFamiliesAsync(global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModifyColumnFamiliesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Atomically performs a series of column family modifications
      ///  on the specified table.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Bigtable.Admin.V2.Table> ModifyColumnFamiliesAsync(global::Google.Bigtable.Admin.V2.ModifyColumnFamiliesRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ModifyColumnFamilies, null, options, request);
      }
      /// <summary>
      ///  Permanently drop/delete a row range from a specified table. The request can
      ///  specify whether to delete all rows in a table, or only those that match a
      ///  particular prefix.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DropRowRange(global::Google.Bigtable.Admin.V2.DropRowRangeRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DropRowRange(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Permanently drop/delete a row range from a specified table. The request can
      ///  specify whether to delete all rows in a table, or only those that match a
      ///  particular prefix.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DropRowRange(global::Google.Bigtable.Admin.V2.DropRowRangeRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DropRowRange, null, options, request);
      }
      /// <summary>
      ///  Permanently drop/delete a row range from a specified table. The request can
      ///  specify whether to delete all rows in a table, or only those that match a
      ///  particular prefix.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DropRowRangeAsync(global::Google.Bigtable.Admin.V2.DropRowRangeRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DropRowRangeAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Permanently drop/delete a row range from a specified table. The request can
      ///  specify whether to delete all rows in a table, or only those that match a
      ///  particular prefix.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DropRowRangeAsync(global::Google.Bigtable.Admin.V2.DropRowRangeRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DropRowRange, null, options, request);
      }
      protected override BigtableTableAdminClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BigtableTableAdminClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(BigtableTableAdminBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateTable, serviceImpl.CreateTable)
          .AddMethod(__Method_ListTables, serviceImpl.ListTables)
          .AddMethod(__Method_GetTable, serviceImpl.GetTable)
          .AddMethod(__Method_DeleteTable, serviceImpl.DeleteTable)
          .AddMethod(__Method_ModifyColumnFamilies, serviceImpl.ModifyColumnFamilies)
          .AddMethod(__Method_DropRowRange, serviceImpl.DropRowRange).Build();
    }

  }
}
#endregion
