// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dataproc/v1/jobs.proto
// Original file comments:
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Cloud.Dataproc.V1 {
  /// <summary>
  ///  The JobController provides methods to manage jobs.
  /// </summary>
  public static class JobController
  {
    static readonly string __ServiceName = "google.cloud.dataproc.v1.JobController";

    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.SubmitJobRequest> __Marshaller_SubmitJobRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.SubmitJobRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.Job> __Marshaller_Job = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.Job.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.GetJobRequest> __Marshaller_GetJobRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.GetJobRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.ListJobsRequest> __Marshaller_ListJobsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.ListJobsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.ListJobsResponse> __Marshaller_ListJobsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.ListJobsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.CancelJobRequest> __Marshaller_CancelJobRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.CancelJobRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Cloud.Dataproc.V1.DeleteJobRequest> __Marshaller_DeleteJobRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Cloud.Dataproc.V1.DeleteJobRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);

    static readonly Method<global::Google.Cloud.Dataproc.V1.SubmitJobRequest, global::Google.Cloud.Dataproc.V1.Job> __Method_SubmitJob = new Method<global::Google.Cloud.Dataproc.V1.SubmitJobRequest, global::Google.Cloud.Dataproc.V1.Job>(
        MethodType.Unary,
        __ServiceName,
        "SubmitJob",
        __Marshaller_SubmitJobRequest,
        __Marshaller_Job);

    static readonly Method<global::Google.Cloud.Dataproc.V1.GetJobRequest, global::Google.Cloud.Dataproc.V1.Job> __Method_GetJob = new Method<global::Google.Cloud.Dataproc.V1.GetJobRequest, global::Google.Cloud.Dataproc.V1.Job>(
        MethodType.Unary,
        __ServiceName,
        "GetJob",
        __Marshaller_GetJobRequest,
        __Marshaller_Job);

    static readonly Method<global::Google.Cloud.Dataproc.V1.ListJobsRequest, global::Google.Cloud.Dataproc.V1.ListJobsResponse> __Method_ListJobs = new Method<global::Google.Cloud.Dataproc.V1.ListJobsRequest, global::Google.Cloud.Dataproc.V1.ListJobsResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListJobs",
        __Marshaller_ListJobsRequest,
        __Marshaller_ListJobsResponse);

    static readonly Method<global::Google.Cloud.Dataproc.V1.CancelJobRequest, global::Google.Cloud.Dataproc.V1.Job> __Method_CancelJob = new Method<global::Google.Cloud.Dataproc.V1.CancelJobRequest, global::Google.Cloud.Dataproc.V1.Job>(
        MethodType.Unary,
        __ServiceName,
        "CancelJob",
        __Marshaller_CancelJobRequest,
        __Marshaller_Job);

    static readonly Method<global::Google.Cloud.Dataproc.V1.DeleteJobRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteJob = new Method<global::Google.Cloud.Dataproc.V1.DeleteJobRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteJob",
        __Marshaller_DeleteJobRequest,
        __Marshaller_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Cloud.Dataproc.V1.JobsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of JobController</summary>
    public abstract class JobControllerBase
    {
      /// <summary>
      ///  Submits a job to a cluster.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Dataproc.V1.Job> SubmitJob(global::Google.Cloud.Dataproc.V1.SubmitJobRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets the resource representation for a job in a project.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Dataproc.V1.Job> GetJob(global::Google.Cloud.Dataproc.V1.GetJobRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Lists regions/{region}/jobs in a project.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Dataproc.V1.ListJobsResponse> ListJobs(global::Google.Cloud.Dataproc.V1.ListJobsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Starts a job cancellation request. To access the job resource
      ///  after cancellation, call
      ///  [regions/{region}/jobs.list](/dataproc/reference/rest/v1/projects.regions.jobs/list) or
      ///  [regions/{region}/jobs.get](/dataproc/reference/rest/v1/projects.regions.jobs/get).
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Cloud.Dataproc.V1.Job> CancelJob(global::Google.Cloud.Dataproc.V1.CancelJobRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Deletes the job from the project. If the job is active, the delete fails,
      ///  and the response returns `FAILED_PRECONDITION`.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteJob(global::Google.Cloud.Dataproc.V1.DeleteJobRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for JobController</summary>
    public class JobControllerClient : ClientBase<JobControllerClient>
    {
      /// <summary>Creates a new client for JobController</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public JobControllerClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for JobController that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public JobControllerClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected JobControllerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected JobControllerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Submits a job to a cluster.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job SubmitJob(global::Google.Cloud.Dataproc.V1.SubmitJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubmitJob(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Submits a job to a cluster.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job SubmitJob(global::Google.Cloud.Dataproc.V1.SubmitJobRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SubmitJob, null, options, request);
      }
      /// <summary>
      ///  Submits a job to a cluster.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> SubmitJobAsync(global::Google.Cloud.Dataproc.V1.SubmitJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubmitJobAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Submits a job to a cluster.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> SubmitJobAsync(global::Google.Cloud.Dataproc.V1.SubmitJobRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SubmitJob, null, options, request);
      }
      /// <summary>
      ///  Gets the resource representation for a job in a project.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job GetJob(global::Google.Cloud.Dataproc.V1.GetJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetJob(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets the resource representation for a job in a project.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job GetJob(global::Google.Cloud.Dataproc.V1.GetJobRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJob, null, options, request);
      }
      /// <summary>
      ///  Gets the resource representation for a job in a project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> GetJobAsync(global::Google.Cloud.Dataproc.V1.GetJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetJobAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets the resource representation for a job in a project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> GetJobAsync(global::Google.Cloud.Dataproc.V1.GetJobRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJob, null, options, request);
      }
      /// <summary>
      ///  Lists regions/{region}/jobs in a project.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.ListJobsResponse ListJobs(global::Google.Cloud.Dataproc.V1.ListJobsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListJobs(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists regions/{region}/jobs in a project.
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.ListJobsResponse ListJobs(global::Google.Cloud.Dataproc.V1.ListJobsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListJobs, null, options, request);
      }
      /// <summary>
      ///  Lists regions/{region}/jobs in a project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.ListJobsResponse> ListJobsAsync(global::Google.Cloud.Dataproc.V1.ListJobsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListJobsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists regions/{region}/jobs in a project.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.ListJobsResponse> ListJobsAsync(global::Google.Cloud.Dataproc.V1.ListJobsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListJobs, null, options, request);
      }
      /// <summary>
      ///  Starts a job cancellation request. To access the job resource
      ///  after cancellation, call
      ///  [regions/{region}/jobs.list](/dataproc/reference/rest/v1/projects.regions.jobs/list) or
      ///  [regions/{region}/jobs.get](/dataproc/reference/rest/v1/projects.regions.jobs/get).
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job CancelJob(global::Google.Cloud.Dataproc.V1.CancelJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CancelJob(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Starts a job cancellation request. To access the job resource
      ///  after cancellation, call
      ///  [regions/{region}/jobs.list](/dataproc/reference/rest/v1/projects.regions.jobs/list) or
      ///  [regions/{region}/jobs.get](/dataproc/reference/rest/v1/projects.regions.jobs/get).
      /// </summary>
      public virtual global::Google.Cloud.Dataproc.V1.Job CancelJob(global::Google.Cloud.Dataproc.V1.CancelJobRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CancelJob, null, options, request);
      }
      /// <summary>
      ///  Starts a job cancellation request. To access the job resource
      ///  after cancellation, call
      ///  [regions/{region}/jobs.list](/dataproc/reference/rest/v1/projects.regions.jobs/list) or
      ///  [regions/{region}/jobs.get](/dataproc/reference/rest/v1/projects.regions.jobs/get).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> CancelJobAsync(global::Google.Cloud.Dataproc.V1.CancelJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CancelJobAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Starts a job cancellation request. To access the job resource
      ///  after cancellation, call
      ///  [regions/{region}/jobs.list](/dataproc/reference/rest/v1/projects.regions.jobs/list) or
      ///  [regions/{region}/jobs.get](/dataproc/reference/rest/v1/projects.regions.jobs/get).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Cloud.Dataproc.V1.Job> CancelJobAsync(global::Google.Cloud.Dataproc.V1.CancelJobRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CancelJob, null, options, request);
      }
      /// <summary>
      ///  Deletes the job from the project. If the job is active, the delete fails,
      ///  and the response returns `FAILED_PRECONDITION`.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteJob(global::Google.Cloud.Dataproc.V1.DeleteJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteJob(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes the job from the project. If the job is active, the delete fails,
      ///  and the response returns `FAILED_PRECONDITION`.
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteJob(global::Google.Cloud.Dataproc.V1.DeleteJobRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteJob, null, options, request);
      }
      /// <summary>
      ///  Deletes the job from the project. If the job is active, the delete fails,
      ///  and the response returns `FAILED_PRECONDITION`.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteJobAsync(global::Google.Cloud.Dataproc.V1.DeleteJobRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteJobAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes the job from the project. If the job is active, the delete fails,
      ///  and the response returns `FAILED_PRECONDITION`.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteJobAsync(global::Google.Cloud.Dataproc.V1.DeleteJobRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteJob, null, options, request);
      }
      protected override JobControllerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new JobControllerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(JobControllerBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SubmitJob, serviceImpl.SubmitJob)
          .AddMethod(__Method_GetJob, serviceImpl.GetJob)
          .AddMethod(__Method_ListJobs, serviceImpl.ListJobs)
          .AddMethod(__Method_CancelJob, serviceImpl.CancelJob)
          .AddMethod(__Method_DeleteJob, serviceImpl.DeleteJob).Build();
    }

  }
}
#endregion
