// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/genomics/v1/reads.proto
// Original file comments:
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Google.Genomics.V1 {
  public static class StreamingReadService
  {
    static readonly string __ServiceName = "google.genomics.v1.StreamingReadService";

    static readonly Marshaller<global::Google.Genomics.V1.StreamReadsRequest> __Marshaller_StreamReadsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.StreamReadsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.StreamReadsResponse> __Marshaller_StreamReadsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.StreamReadsResponse.Parser.ParseFrom);

    static readonly Method<global::Google.Genomics.V1.StreamReadsRequest, global::Google.Genomics.V1.StreamReadsResponse> __Method_StreamReads = new Method<global::Google.Genomics.V1.StreamReadsRequest, global::Google.Genomics.V1.StreamReadsResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "StreamReads",
        __Marshaller_StreamReadsRequest,
        __Marshaller_StreamReadsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Genomics.V1.ReadsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StreamingReadService</summary>
    public abstract class StreamingReadServiceBase
    {
      /// <summary>
      ///  Returns a stream of all the reads matching the search request, ordered
      ///  by reference name, position, and ID.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task StreamReads(global::Google.Genomics.V1.StreamReadsRequest request, IServerStreamWriter<global::Google.Genomics.V1.StreamReadsResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StreamingReadService</summary>
    public class StreamingReadServiceClient : ClientBase<StreamingReadServiceClient>
    {
      /// <summary>Creates a new client for StreamingReadService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StreamingReadServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StreamingReadService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StreamingReadServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StreamingReadServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StreamingReadServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Returns a stream of all the reads matching the search request, ordered
      ///  by reference name, position, and ID.
      /// </summary>
      public virtual AsyncServerStreamingCall<global::Google.Genomics.V1.StreamReadsResponse> StreamReads(global::Google.Genomics.V1.StreamReadsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StreamReads(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Returns a stream of all the reads matching the search request, ordered
      ///  by reference name, position, and ID.
      /// </summary>
      public virtual AsyncServerStreamingCall<global::Google.Genomics.V1.StreamReadsResponse> StreamReads(global::Google.Genomics.V1.StreamReadsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamReads, null, options, request);
      }
      protected override StreamingReadServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StreamingReadServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(StreamingReadServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StreamReads, serviceImpl.StreamReads).Build();
    }

  }
  /// <summary>
  ///  The Readstore. A data store for DNA sequencing Reads.
  /// </summary>
  public static class ReadServiceV1
  {
    static readonly string __ServiceName = "google.genomics.v1.ReadServiceV1";

    static readonly Marshaller<global::Google.Genomics.V1.ImportReadGroupSetsRequest> __Marshaller_ImportReadGroupSetsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.ImportReadGroupSetsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.LongRunning.Operation> __Marshaller_Operation = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.LongRunning.Operation.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.ExportReadGroupSetRequest> __Marshaller_ExportReadGroupSetRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.ExportReadGroupSetRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.SearchReadGroupSetsRequest> __Marshaller_SearchReadGroupSetsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.SearchReadGroupSetsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.SearchReadGroupSetsResponse> __Marshaller_SearchReadGroupSetsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.SearchReadGroupSetsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.UpdateReadGroupSetRequest> __Marshaller_UpdateReadGroupSetRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.UpdateReadGroupSetRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.ReadGroupSet> __Marshaller_ReadGroupSet = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.ReadGroupSet.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.DeleteReadGroupSetRequest> __Marshaller_DeleteReadGroupSetRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.DeleteReadGroupSetRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.GetReadGroupSetRequest> __Marshaller_GetReadGroupSetRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.GetReadGroupSetRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.ListCoverageBucketsRequest> __Marshaller_ListCoverageBucketsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.ListCoverageBucketsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.ListCoverageBucketsResponse> __Marshaller_ListCoverageBucketsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.ListCoverageBucketsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.SearchReadsRequest> __Marshaller_SearchReadsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.SearchReadsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Genomics.V1.SearchReadsResponse> __Marshaller_SearchReadsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Genomics.V1.SearchReadsResponse.Parser.ParseFrom);

    static readonly Method<global::Google.Genomics.V1.ImportReadGroupSetsRequest, global::Google.LongRunning.Operation> __Method_ImportReadGroupSets = new Method<global::Google.Genomics.V1.ImportReadGroupSetsRequest, global::Google.LongRunning.Operation>(
        MethodType.Unary,
        __ServiceName,
        "ImportReadGroupSets",
        __Marshaller_ImportReadGroupSetsRequest,
        __Marshaller_Operation);

    static readonly Method<global::Google.Genomics.V1.ExportReadGroupSetRequest, global::Google.LongRunning.Operation> __Method_ExportReadGroupSet = new Method<global::Google.Genomics.V1.ExportReadGroupSetRequest, global::Google.LongRunning.Operation>(
        MethodType.Unary,
        __ServiceName,
        "ExportReadGroupSet",
        __Marshaller_ExportReadGroupSetRequest,
        __Marshaller_Operation);

    static readonly Method<global::Google.Genomics.V1.SearchReadGroupSetsRequest, global::Google.Genomics.V1.SearchReadGroupSetsResponse> __Method_SearchReadGroupSets = new Method<global::Google.Genomics.V1.SearchReadGroupSetsRequest, global::Google.Genomics.V1.SearchReadGroupSetsResponse>(
        MethodType.Unary,
        __ServiceName,
        "SearchReadGroupSets",
        __Marshaller_SearchReadGroupSetsRequest,
        __Marshaller_SearchReadGroupSetsResponse);

    static readonly Method<global::Google.Genomics.V1.UpdateReadGroupSetRequest, global::Google.Genomics.V1.ReadGroupSet> __Method_UpdateReadGroupSet = new Method<global::Google.Genomics.V1.UpdateReadGroupSetRequest, global::Google.Genomics.V1.ReadGroupSet>(
        MethodType.Unary,
        __ServiceName,
        "UpdateReadGroupSet",
        __Marshaller_UpdateReadGroupSetRequest,
        __Marshaller_ReadGroupSet);

    static readonly Method<global::Google.Genomics.V1.DeleteReadGroupSetRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteReadGroupSet = new Method<global::Google.Genomics.V1.DeleteReadGroupSetRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteReadGroupSet",
        __Marshaller_DeleteReadGroupSetRequest,
        __Marshaller_Empty);

    static readonly Method<global::Google.Genomics.V1.GetReadGroupSetRequest, global::Google.Genomics.V1.ReadGroupSet> __Method_GetReadGroupSet = new Method<global::Google.Genomics.V1.GetReadGroupSetRequest, global::Google.Genomics.V1.ReadGroupSet>(
        MethodType.Unary,
        __ServiceName,
        "GetReadGroupSet",
        __Marshaller_GetReadGroupSetRequest,
        __Marshaller_ReadGroupSet);

    static readonly Method<global::Google.Genomics.V1.ListCoverageBucketsRequest, global::Google.Genomics.V1.ListCoverageBucketsResponse> __Method_ListCoverageBuckets = new Method<global::Google.Genomics.V1.ListCoverageBucketsRequest, global::Google.Genomics.V1.ListCoverageBucketsResponse>(
        MethodType.Unary,
        __ServiceName,
        "ListCoverageBuckets",
        __Marshaller_ListCoverageBucketsRequest,
        __Marshaller_ListCoverageBucketsResponse);

    static readonly Method<global::Google.Genomics.V1.SearchReadsRequest, global::Google.Genomics.V1.SearchReadsResponse> __Method_SearchReads = new Method<global::Google.Genomics.V1.SearchReadsRequest, global::Google.Genomics.V1.SearchReadsResponse>(
        MethodType.Unary,
        __ServiceName,
        "SearchReads",
        __Marshaller_SearchReadsRequest,
        __Marshaller_SearchReadsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Genomics.V1.ReadsReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of ReadServiceV1</summary>
    public abstract class ReadServiceV1Base
    {
      /// <summary>
      ///  Creates read group sets by asynchronously importing the provided
      ///  information.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  The caller must have WRITE permissions to the dataset.
      ///
      ///  ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import
      ///
      ///  - Tags will be converted to strings - tag types are not preserved
      ///  - Comments (`@CO`) in the input file header will not be preserved
      ///  - Original header order of references (`@SQ`) will not be preserved
      ///  - Any reverse stranded unmapped reads will be reverse complemented, and
      ///  their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
      ///  - Unmapped reads will be stripped of positional information (reference name
      ///  and position)
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.LongRunning.Operation> ImportReadGroupSets(global::Google.Genomics.V1.ImportReadGroupSetsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Exports a read group set to a BAM file in Google Cloud Storage.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Note that currently there may be some differences between exported BAM
      ///  files and the original BAM file at the time of import. See
      ///  [ImportReadGroupSets][google.genomics.v1.ReadServiceV1.ImportReadGroupSets]
      ///  for caveats.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.LongRunning.Operation> ExportReadGroupSet(global::Google.Genomics.V1.ExportReadGroupSetRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Searches for read group sets matching the criteria.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Genomics.V1.SearchReadGroupSetsResponse> SearchReadGroupSets(global::Google.Genomics.V1.SearchReadGroupSetsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Updates a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  This method supports patch semantics.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Genomics.V1.ReadGroupSet> UpdateReadGroupSet(global::Google.Genomics.V1.UpdateReadGroupSetRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Deletes a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteReadGroupSet(global::Google.Genomics.V1.DeleteReadGroupSetRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets a read group set by ID.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Genomics.V1.ReadGroupSet> GetReadGroupSet(global::Google.Genomics.V1.GetReadGroupSetRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Lists fixed width coverage buckets for a read group set, each of which
      ///  correspond to a range of a reference sequence. Each bucket summarizes
      ///  coverage information across its corresponding genomic range.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Coverage is defined as the number of reads which are aligned to a given
      ///  base in the reference sequence. Coverage buckets are available at several
      ///  precomputed bucket widths, enabling retrieval of various coverage 'zoom
      ///  levels'. The caller must have READ permissions for the target read group
      ///  set.
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Genomics.V1.ListCoverageBucketsResponse> ListCoverageBuckets(global::Google.Genomics.V1.ListCoverageBucketsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Gets a list of reads for one or more read group sets.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Reads search operates over a genomic coordinate space of reference sequence
      ///  &amp; position defined over the reference sequences to which the requested
      ///  read group sets are aligned.
      ///
      ///  If a target positional range is specified, search returns all reads whose
      ///  alignment to the reference genome overlap the range. A query which
      ///  specifies only read group set IDs yields all reads in those read group
      ///  sets, including unmapped reads.
      ///
      ///  All reads returned (including reads on subsequent pages) are ordered by
      ///  genomic coordinate (by reference sequence, then position). Reads with
      ///  equivalent genomic coordinates are returned in an unspecified order. This
      ///  order is consistent, such that two queries for the same content (regardless
      ///  of page size) yield reads in the same order across their respective streams
      ///  of paginated responses.
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Google.Genomics.V1.SearchReadsResponse> SearchReads(global::Google.Genomics.V1.SearchReadsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ReadServiceV1</summary>
    public class ReadServiceV1Client : ClientBase<ReadServiceV1Client>
    {
      /// <summary>Creates a new client for ReadServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ReadServiceV1Client(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ReadServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ReadServiceV1Client(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ReadServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ReadServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Creates read group sets by asynchronously importing the provided
      ///  information.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  The caller must have WRITE permissions to the dataset.
      ///
      ///  ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import
      ///
      ///  - Tags will be converted to strings - tag types are not preserved
      ///  - Comments (`@CO`) in the input file header will not be preserved
      ///  - Original header order of references (`@SQ`) will not be preserved
      ///  - Any reverse stranded unmapped reads will be reverse complemented, and
      ///  their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
      ///  - Unmapped reads will be stripped of positional information (reference name
      ///  and position)
      /// </summary>
      public virtual global::Google.LongRunning.Operation ImportReadGroupSets(global::Google.Genomics.V1.ImportReadGroupSetsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportReadGroupSets(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates read group sets by asynchronously importing the provided
      ///  information.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  The caller must have WRITE permissions to the dataset.
      ///
      ///  ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import
      ///
      ///  - Tags will be converted to strings - tag types are not preserved
      ///  - Comments (`@CO`) in the input file header will not be preserved
      ///  - Original header order of references (`@SQ`) will not be preserved
      ///  - Any reverse stranded unmapped reads will be reverse complemented, and
      ///  their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
      ///  - Unmapped reads will be stripped of positional information (reference name
      ///  and position)
      /// </summary>
      public virtual global::Google.LongRunning.Operation ImportReadGroupSets(global::Google.Genomics.V1.ImportReadGroupSetsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImportReadGroupSets, null, options, request);
      }
      /// <summary>
      ///  Creates read group sets by asynchronously importing the provided
      ///  information.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  The caller must have WRITE permissions to the dataset.
      ///
      ///  ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import
      ///
      ///  - Tags will be converted to strings - tag types are not preserved
      ///  - Comments (`@CO`) in the input file header will not be preserved
      ///  - Original header order of references (`@SQ`) will not be preserved
      ///  - Any reverse stranded unmapped reads will be reverse complemented, and
      ///  their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
      ///  - Unmapped reads will be stripped of positional information (reference name
      ///  and position)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> ImportReadGroupSetsAsync(global::Google.Genomics.V1.ImportReadGroupSetsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportReadGroupSetsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Creates read group sets by asynchronously importing the provided
      ///  information.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  The caller must have WRITE permissions to the dataset.
      ///
      ///  ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import
      ///
      ///  - Tags will be converted to strings - tag types are not preserved
      ///  - Comments (`@CO`) in the input file header will not be preserved
      ///  - Original header order of references (`@SQ`) will not be preserved
      ///  - Any reverse stranded unmapped reads will be reverse complemented, and
      ///  their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
      ///  - Unmapped reads will be stripped of positional information (reference name
      ///  and position)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> ImportReadGroupSetsAsync(global::Google.Genomics.V1.ImportReadGroupSetsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImportReadGroupSets, null, options, request);
      }
      /// <summary>
      ///  Exports a read group set to a BAM file in Google Cloud Storage.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Note that currently there may be some differences between exported BAM
      ///  files and the original BAM file at the time of import. See
      ///  [ImportReadGroupSets][google.genomics.v1.ReadServiceV1.ImportReadGroupSets]
      ///  for caveats.
      /// </summary>
      public virtual global::Google.LongRunning.Operation ExportReadGroupSet(global::Google.Genomics.V1.ExportReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ExportReadGroupSet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Exports a read group set to a BAM file in Google Cloud Storage.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Note that currently there may be some differences between exported BAM
      ///  files and the original BAM file at the time of import. See
      ///  [ImportReadGroupSets][google.genomics.v1.ReadServiceV1.ImportReadGroupSets]
      ///  for caveats.
      /// </summary>
      public virtual global::Google.LongRunning.Operation ExportReadGroupSet(global::Google.Genomics.V1.ExportReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExportReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Exports a read group set to a BAM file in Google Cloud Storage.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Note that currently there may be some differences between exported BAM
      ///  files and the original BAM file at the time of import. See
      ///  [ImportReadGroupSets][google.genomics.v1.ReadServiceV1.ImportReadGroupSets]
      ///  for caveats.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> ExportReadGroupSetAsync(global::Google.Genomics.V1.ExportReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ExportReadGroupSetAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Exports a read group set to a BAM file in Google Cloud Storage.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Note that currently there may be some differences between exported BAM
      ///  files and the original BAM file at the time of import. See
      ///  [ImportReadGroupSets][google.genomics.v1.ReadServiceV1.ImportReadGroupSets]
      ///  for caveats.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.LongRunning.Operation> ExportReadGroupSetAsync(global::Google.Genomics.V1.ExportReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExportReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Searches for read group sets matching the criteria.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      /// </summary>
      public virtual global::Google.Genomics.V1.SearchReadGroupSetsResponse SearchReadGroupSets(global::Google.Genomics.V1.SearchReadGroupSetsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SearchReadGroupSets(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Searches for read group sets matching the criteria.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      /// </summary>
      public virtual global::Google.Genomics.V1.SearchReadGroupSetsResponse SearchReadGroupSets(global::Google.Genomics.V1.SearchReadGroupSetsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchReadGroupSets, null, options, request);
      }
      /// <summary>
      ///  Searches for read group sets matching the criteria.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.SearchReadGroupSetsResponse> SearchReadGroupSetsAsync(global::Google.Genomics.V1.SearchReadGroupSetsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SearchReadGroupSetsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Searches for read group sets matching the criteria.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.SearchReadGroupSetsResponse> SearchReadGroupSetsAsync(global::Google.Genomics.V1.SearchReadGroupSetsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchReadGroupSets, null, options, request);
      }
      /// <summary>
      ///  Updates a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  This method supports patch semantics.
      /// </summary>
      public virtual global::Google.Genomics.V1.ReadGroupSet UpdateReadGroupSet(global::Google.Genomics.V1.UpdateReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateReadGroupSet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  This method supports patch semantics.
      /// </summary>
      public virtual global::Google.Genomics.V1.ReadGroupSet UpdateReadGroupSet(global::Google.Genomics.V1.UpdateReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Updates a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  This method supports patch semantics.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ReadGroupSet> UpdateReadGroupSetAsync(global::Google.Genomics.V1.UpdateReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateReadGroupSetAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Updates a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  This method supports patch semantics.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ReadGroupSet> UpdateReadGroupSetAsync(global::Google.Genomics.V1.UpdateReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Deletes a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteReadGroupSet(global::Google.Genomics.V1.DeleteReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteReadGroupSet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteReadGroupSet(global::Google.Genomics.V1.DeleteReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Deletes a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteReadGroupSetAsync(global::Google.Genomics.V1.DeleteReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteReadGroupSetAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Deletes a read group set.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteReadGroupSetAsync(global::Google.Genomics.V1.DeleteReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Gets a read group set by ID.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::Google.Genomics.V1.ReadGroupSet GetReadGroupSet(global::Google.Genomics.V1.GetReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetReadGroupSet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets a read group set by ID.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual global::Google.Genomics.V1.ReadGroupSet GetReadGroupSet(global::Google.Genomics.V1.GetReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Gets a read group set by ID.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ReadGroupSet> GetReadGroupSetAsync(global::Google.Genomics.V1.GetReadGroupSetRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetReadGroupSetAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets a read group set by ID.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ReadGroupSet> GetReadGroupSetAsync(global::Google.Genomics.V1.GetReadGroupSetRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetReadGroupSet, null, options, request);
      }
      /// <summary>
      ///  Lists fixed width coverage buckets for a read group set, each of which
      ///  correspond to a range of a reference sequence. Each bucket summarizes
      ///  coverage information across its corresponding genomic range.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Coverage is defined as the number of reads which are aligned to a given
      ///  base in the reference sequence. Coverage buckets are available at several
      ///  precomputed bucket widths, enabling retrieval of various coverage 'zoom
      ///  levels'. The caller must have READ permissions for the target read group
      ///  set.
      /// </summary>
      public virtual global::Google.Genomics.V1.ListCoverageBucketsResponse ListCoverageBuckets(global::Google.Genomics.V1.ListCoverageBucketsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListCoverageBuckets(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists fixed width coverage buckets for a read group set, each of which
      ///  correspond to a range of a reference sequence. Each bucket summarizes
      ///  coverage information across its corresponding genomic range.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Coverage is defined as the number of reads which are aligned to a given
      ///  base in the reference sequence. Coverage buckets are available at several
      ///  precomputed bucket widths, enabling retrieval of various coverage 'zoom
      ///  levels'. The caller must have READ permissions for the target read group
      ///  set.
      /// </summary>
      public virtual global::Google.Genomics.V1.ListCoverageBucketsResponse ListCoverageBuckets(global::Google.Genomics.V1.ListCoverageBucketsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListCoverageBuckets, null, options, request);
      }
      /// <summary>
      ///  Lists fixed width coverage buckets for a read group set, each of which
      ///  correspond to a range of a reference sequence. Each bucket summarizes
      ///  coverage information across its corresponding genomic range.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Coverage is defined as the number of reads which are aligned to a given
      ///  base in the reference sequence. Coverage buckets are available at several
      ///  precomputed bucket widths, enabling retrieval of various coverage 'zoom
      ///  levels'. The caller must have READ permissions for the target read group
      ///  set.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ListCoverageBucketsResponse> ListCoverageBucketsAsync(global::Google.Genomics.V1.ListCoverageBucketsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListCoverageBucketsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Lists fixed width coverage buckets for a read group set, each of which
      ///  correspond to a range of a reference sequence. Each bucket summarizes
      ///  coverage information across its corresponding genomic range.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Coverage is defined as the number of reads which are aligned to a given
      ///  base in the reference sequence. Coverage buckets are available at several
      ///  precomputed bucket widths, enabling retrieval of various coverage 'zoom
      ///  levels'. The caller must have READ permissions for the target read group
      ///  set.
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.ListCoverageBucketsResponse> ListCoverageBucketsAsync(global::Google.Genomics.V1.ListCoverageBucketsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListCoverageBuckets, null, options, request);
      }
      /// <summary>
      ///  Gets a list of reads for one or more read group sets.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Reads search operates over a genomic coordinate space of reference sequence
      ///  &amp; position defined over the reference sequences to which the requested
      ///  read group sets are aligned.
      ///
      ///  If a target positional range is specified, search returns all reads whose
      ///  alignment to the reference genome overlap the range. A query which
      ///  specifies only read group set IDs yields all reads in those read group
      ///  sets, including unmapped reads.
      ///
      ///  All reads returned (including reads on subsequent pages) are ordered by
      ///  genomic coordinate (by reference sequence, then position). Reads with
      ///  equivalent genomic coordinates are returned in an unspecified order. This
      ///  order is consistent, such that two queries for the same content (regardless
      ///  of page size) yield reads in the same order across their respective streams
      ///  of paginated responses.
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      /// </summary>
      public virtual global::Google.Genomics.V1.SearchReadsResponse SearchReads(global::Google.Genomics.V1.SearchReadsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SearchReads(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets a list of reads for one or more read group sets.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Reads search operates over a genomic coordinate space of reference sequence
      ///  &amp; position defined over the reference sequences to which the requested
      ///  read group sets are aligned.
      ///
      ///  If a target positional range is specified, search returns all reads whose
      ///  alignment to the reference genome overlap the range. A query which
      ///  specifies only read group set IDs yields all reads in those read group
      ///  sets, including unmapped reads.
      ///
      ///  All reads returned (including reads on subsequent pages) are ordered by
      ///  genomic coordinate (by reference sequence, then position). Reads with
      ///  equivalent genomic coordinates are returned in an unspecified order. This
      ///  order is consistent, such that two queries for the same content (regardless
      ///  of page size) yield reads in the same order across their respective streams
      ///  of paginated responses.
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      /// </summary>
      public virtual global::Google.Genomics.V1.SearchReadsResponse SearchReads(global::Google.Genomics.V1.SearchReadsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchReads, null, options, request);
      }
      /// <summary>
      ///  Gets a list of reads for one or more read group sets.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Reads search operates over a genomic coordinate space of reference sequence
      ///  &amp; position defined over the reference sequences to which the requested
      ///  read group sets are aligned.
      ///
      ///  If a target positional range is specified, search returns all reads whose
      ///  alignment to the reference genome overlap the range. A query which
      ///  specifies only read group set IDs yields all reads in those read group
      ///  sets, including unmapped reads.
      ///
      ///  All reads returned (including reads on subsequent pages) are ordered by
      ///  genomic coordinate (by reference sequence, then position). Reads with
      ///  equivalent genomic coordinates are returned in an unspecified order. This
      ///  order is consistent, such that two queries for the same content (regardless
      ///  of page size) yield reads in the same order across their respective streams
      ///  of paginated responses.
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.SearchReadsResponse> SearchReadsAsync(global::Google.Genomics.V1.SearchReadsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SearchReadsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Gets a list of reads for one or more read group sets.
      ///
      ///  For the definitions of read group sets and other genomics resources, see
      ///  [Fundamentals of Google
      ///  Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      ///
      ///  Reads search operates over a genomic coordinate space of reference sequence
      ///  &amp; position defined over the reference sequences to which the requested
      ///  read group sets are aligned.
      ///
      ///  If a target positional range is specified, search returns all reads whose
      ///  alignment to the reference genome overlap the range. A query which
      ///  specifies only read group set IDs yields all reads in those read group
      ///  sets, including unmapped reads.
      ///
      ///  All reads returned (including reads on subsequent pages) are ordered by
      ///  genomic coordinate (by reference sequence, then position). Reads with
      ///  equivalent genomic coordinates are returned in an unspecified order. This
      ///  order is consistent, such that two queries for the same content (regardless
      ///  of page size) yield reads in the same order across their respective streams
      ///  of paginated responses.
      ///
      ///  Implements
      ///  [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      /// </summary>
      public virtual AsyncUnaryCall<global::Google.Genomics.V1.SearchReadsResponse> SearchReadsAsync(global::Google.Genomics.V1.SearchReadsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchReads, null, options, request);
      }
      protected override ReadServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new ReadServiceV1Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(ReadServiceV1Base serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ImportReadGroupSets, serviceImpl.ImportReadGroupSets)
          .AddMethod(__Method_ExportReadGroupSet, serviceImpl.ExportReadGroupSet)
          .AddMethod(__Method_SearchReadGroupSets, serviceImpl.SearchReadGroupSets)
          .AddMethod(__Method_UpdateReadGroupSet, serviceImpl.UpdateReadGroupSet)
          .AddMethod(__Method_DeleteReadGroupSet, serviceImpl.DeleteReadGroupSet)
          .AddMethod(__Method_GetReadGroupSet, serviceImpl.GetReadGroupSet)
          .AddMethod(__Method_ListCoverageBuckets, serviceImpl.ListCoverageBuckets)
          .AddMethod(__Method_SearchReads, serviceImpl.SearchReads).Build();
    }

  }
}
#endregion
